#!/usr/bin/env bash

#	from https://akrabat.com/add-touchid-authentication-to-sudo/

set -e

case `grep -F "pam_tid" /etc/pam.d/sudo >/dev/null; echo $?` in
  0)
    echo "TouchID unlock already in place"
    exit 0
    ;;
  1)
    sudo sed -i '' '1a\
auth       sufficient     pam_tid.so
    ' /etc/pam.d/sudo

    echo "TouchID unlock enabled"
    ;;
  *)
    echo "Error trying to read /etc/pam.d/sudo"
    ;;
esac
